# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

inhibit_all_warnings!

pod 'FirebaseAuth'
pod 'FirebaseFirestore'
pod 'FirebaseStorage'

target 'DiplomaProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DiplomaProject

end
